replicaCount: 1

image:
  repository: binwiederhier/ntfy
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"

service:
  type: ClusterIP
  port: 80

configMap:
  enabled: true
  name: ntfy

statefulSet:
  enabled: false
  cache:
    enabled: true
    storage: 1Gi

deployment:
  enabled: false

pod:
  enabled: false

