{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:
  ntfy.yml: |
{{ .Values.configMap.data | indent 4 }}
{{- end }}

